{"name": "Проверка принятия заказа без айди", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <tests.orders.test_order_accept.TestOrderAccept object at 0x00000254A46F8E90>\nregister_new_courier_and_return_login_password = ['fyiopwykpw', 'fyiopwykpw', 'fyiopwykpw', 289120]\n\n    @allure.title('Проверка принятия заказа без айди')\n    @allure.issue('', 'Фактические status_code и text отличны от заявленных в документации')\n    def test_take_order_without_order_id(self, register_new_courier_and_return_login_password):\n    \n        courier = register_new_courier_and_return_login_password[3]\n        response = requests.put(f'{URL}?courierId={courier}')\n    \n>       assert response.status_code == 400  # BUG: Сервер возвращает 404\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\orders\\test_order_accept.py:27: AssertionError"}, "start": 1712677286886, "stop": 1712677287936, "uuid": "fe3cafbe-1cf9-462e-92d6-0ee5db19b711", "historyId": "7037b0ca4b3f34d58da64c142fedea0f", "testCaseId": "7037b0ca4b3f34d58da64c142fedea0f", "fullName": "tests.orders.test_order_accept.TestOrderAccept#test_take_order_without_order_id", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_order_accept"}, {"name": "subSuite", "value": "TestOrderAccept"}, {"name": "host", "value": "DESKTOP-P4QDAQP"}, {"name": "thread", "value": "5944-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_order_accept"}], "links": [{"type": "issue", "name": "Фактические status_code и text отличны от заявленных в документации"}]}